### ISSUE TITLE
Failed product export in loop

### ISSUE THREAD

**Issue by evensis** [realtimedespatch/orderflow-magento-module#11]
Hi guys,

Have a new issue, when a product export fails, it seems to stick inside the cron. There are some products that have been accidentally exported which are marketing based skus for a bespoke feature on our store.

Orderflow is asking for a category to assign, but I'd rather just remove the particular export as these aren't products that should be in the export.

It would be handy for a catalog/product level attribute, where we can have a sku level boolean dropdown that specifies whether or not this particular product can be exported.

However, in the interim, can you let me know how I can get these product export out of its infinite export loop? Come back after the weekend to find it had tried 120+ times to export and the magento message system is riddled with critical errors due to this.

Had a poke through the realtimedespatch_\* tables, but noticing a lot of compressed data so it's somewhat difficult to isolate the particular export and remove it from there.

Thanks.

**Comment by tom-6x6** [comment]
Hi @evensis 

I'll look into adding an exportable attribute to the orderflow tab on the product edit view. In the meantime, I believe you are able to stop the product exporting by setting the exported attribute within the order flow tab to 'yes'.

Please see the attached screeshot:

![orderflow](https://cloud.githubusercontent.com/assets/11460232/8430393/d07eab2c-1f28-11e5-969d-66bf2146ad00.png)

Cheers

Tom

**Comment by evensis** [comment]
Hi @thombirch,

Thanks for that, resolved the issue, no longer sending them down every half hour!

Cheers.
