### ISSUE TITLE
Additional sales_flat_order_grid columns are missing from Enterprise_SalesArchive enterprise_sales_order_grid_archive

### ISSUE THREAD

**Issue by Demoli** [realtimedespatch/orderflow-magento-module#17]
The module adds 3 additional columns to `sales_flat_order_grid`.

These columns do not exist in the Enterprise_SalesArchive module `enterprise_sales_order_grid_archive` table, which causes union selects to fail.

This specifically causes an issue in the Customer admin "Recent Orders" tab, as it attempts to union the two tables to get a complete list of recent orders.

The SQL that fails is:

```
SELECT 
        COUNT(*)
    FROM
        (SELECT 
            `main_table`.*
        FROM
            `sales_flat_order_grid` AS `main_table`
        WHERE
            (main_table.customer_id = '[Customer ID]') UNION ALL SELECT 
            `main_table`.*
        FROM
            `enterprise_sales_order_grid_archive` AS `main_table`
        WHERE
            (main_table.customer_id = [Customer ID])) AS `a`
```

With error:
`Error Code: 1222. The used SELECT statements have a different number of columns`

**Comment by medmek** [comment]
Hi, 

so is it safe to say we only need to add those additional columns in the second table, 
will this create duplicates since in the enterprise table those columns are empty ? if so, I think we should fill the second, 

Thank you
