### ISSUE TITLE
Stock Level Import

### ISSUE THREAD

**Issue by evensis** [realtimedespatch/orderflow-magento-module#2]
When importing stock, negative quantities are imported into Magento.

This poses a problem, in that configurables won't drop off categories if their constituent children have negative product stock quantities even when is_in_stock and stock_status is set to 0. I believe this is a result of a bug in the backorder functionality of Magento.

We don't use backorders, so I've simply written in a ternary at lines 45 and 47 of Model/Service/Importer/Inventory.php with:

$body->value < 0 ? 0 : $body->value

Although for a community release it should include some sort of support for detecting if backorders are enabled, and if so then update with negative quantities.

**Comment by tom-6x6** [comment]
Thanks for highlighting @evensis 

We'll definitely look at adding the above as a configurable option via the admin panel.

**Comment by klw1** [comment]
With @charliearmor

**Comment by charliearmor** [comment]
Tom

Could you email me an estimate for the work you think this will require.

Ta

Charlie
