### ISSUE TITLE
Orderflow Schedule View Broken

### ISSUE THREAD

**Issue by evensis** [realtimedespatch/orderflow-magento-module#5]
Hi guys,

I didn't notice this in Enterprise 1.14.1, however, in Enterprise 1.14.2 it appears the schedule list (accessible by: orderflow -> schedule), presents with a blank admin page (the usual menu system is there but something is breaking the grid look).

I've had a quick look, but looks like its slightly further in and unfortunately don't have the time to debug further in.

Interesting thing is there are no errors whatsoever, usually its XML related when I see no errors but may well be wrong.

Thanks.

**Comment by tom-6x6** [comment]
Thanks @evensis. I'll investigate further.

**Comment by tom-6x6** [comment]
Hi @evensis, I've attempted unsuccessfully to replicate the above this morning. The schedule grid works as expected for myself on 1.14.1, and 1.14.2. 

Please let me know if you are able to find more information.

**Comment by evensis** [comment]
Hi @thombirch,

I will have a look, i've cleared up some rewrite conflicts with the sixbysix module which hasn't fixed it unfortunately (was hoping it would), so will have a deeper dig this afternoon.

Thanks.

**Comment by evensis** [comment]
Hi @thombirch 

Fixed it, we initially installed the module off of magentoconnect for 1.14.2, it seems the release misses the following:

```
   <adminhtml_processschedule_index>
       <reference name="messages">
           <action method="addNotice" translate="message">
               <message>The schedule shows the pending queue of incoming and outgoing messages waiting to be exchanged with OrderFlow and the results of the last attempted exchange for each message type.</message>
           </action>
       </reference>
        <reference name="content">
            <block type="realtimedespatch/adminhtml_process_schedule" name="process_schedule" />
        </reference>
    </adminhtml_processschedule_index>
```

Suspicion confirmed it was xml related!

Maybe worth baring in mind for the Magentoconnect release, as we ran composer and as far as it was concerned it was up to date.

I installed the tar ball that you listed on the github page, and I noticed a ton of create modes on git that werent part of the magentoconnect release nor the composer updates. I suspect the magentoconnect release is inherently broken.

Thanks

**Comment by ghost** [comment]
Hi @evensis 

Thank you for the prompt feedback. @klw1 are you able to update the connect release please to reflect the latest changes, or are we removing support for install via connect altogether?

Thanks

**Comment by klw1** [comment]
Thanks @evensis .
@thomb2233 , I'll update connect based on these latest updates and the composer-free version.
As you know, it's just a pain packaging it up for connect.

cc @charliearmor

**Comment by klw1** [comment]
Forgot to say -  connect updated.
